Your-Planet/back-end

- src/main/java/kr/co/yourplanet/ypbackend/business/user/controller/MemberController.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
> feat : 약관 동의 일자 필드 추가

- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/RegisterForm.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
- src/main/resources/application.yaml
> feat : 비밀번호 정책 적용 (소문자,대문자,숫자,특수문자 중 3가지 이상 사용)

- src/main/java/kr/co/yourplanet/ypbackend/YpBackendApplication.java
- src/main/java/kr/co/yourplanet/ypbackend/business/task/controller/TaskController.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/controller/MemberController.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/MemberSalt.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/repository/MemberRepository.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
- src/main/java/kr/co/yourplanet/ypbackend/common/encrypt/EncryptManager.java
- src/main/java/kr/co/yourplanet/ypbackend/common/encrypt/EncryptProperties.java
- src/main/java/kr/co/yourplanet/ypbackend/config/SwaggerConfig.java
- src/main/java/kr/co/yourplanet/ypbackend/jwt/JwtPrincipal.java
- src/main/java/kr/co/yourplanet/ypbackend/jwt/JwtTokenProvider.java
- src/main/resources/application.yaml
> feat : EncryptManager 추가 / password 암호화 적용

- src/main/java/kr/co/yourplanet/ypbackend/business/user/controller/MemberController.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/JoinForm.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
- src/main/java/kr/co/yourplanet/ypbackend/common/encrypt/EncryptManager.java
> feat : 회원가입시 필수약관 및 선택약관 필드 추가

- src/main/java/kr/co/yourplanet/ypbackend/business/task/domain/Task.java
- src/main/java/kr/co/yourplanet/ypbackend/business/task/service/TaskService.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/JoinForm.java
- src/main/java/kr/co/yourplanet/ypbackend/common/enums/MemberType.java
> [refactor] rename advertiser to sponsor

- src/main/java/kr/co/yourplanet/ypbackend/business/user/controller/MemberController.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/JoinForm.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
- src/main/java/kr/co/yourplanet/ypbackend/common/exception/GlobalExceptionHandler.java
* 회원가입 API : instagramAccessToken 필드 추가
* 회원가입 API : @Valid 오류 메시지 추가
* 로그인 실패 오류 메시지 수정
> YP-132 Merge

- src/main/java/kr/co/yourplanet/ypbackend/business/portfolio/domain/Category.java
- src/main/java/kr/co/yourplanet/ypbackend/business/portfolio/domain/Portfolio.java
- src/main/java/kr/co/yourplanet/ypbackend/business/portfolio/domain/PortfolioCategoryMap.java
- src/main/java/kr/co/yourplanet/ypbackend/business/portfolio/domain/PortfolioLink.java
- src/main/java/kr/co/yourplanet/ypbackend/business/task/domain/Task.java
- src/main/java/kr/co/yourplanet/ypbackend/business/task/domain/TaskHistory.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/MemberSalt.java
- src/main/java/kr/co/yourplanet/ypbackend/common/domain/BasicColumn.java
> [feat] BasicColumn 추가 (create_dtm, update_dtm)

- src/main/java/kr/co/yourplanet/ypbackend/business/user/domain/Member.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/JoinForm.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
> [feat] 약관정보 클래스화 및 필수약관 체크 추가(개인정보동의 여부)

- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/TermsInfo.java
> [feat] 약관정보 클래스화 누락건 커밋

- src/main/java/kr/co/yourplanet/ypbackend/business/user/controller/MemberController.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/dto/MemberValidateForm.java
- src/main/java/kr/co/yourplanet/ypbackend/business/user/service/MemberService.java
일감 정보 : https://your-planet.atlassian.net/browse/YP-149
> Feat : 사용자의 ID, Email, name을 입력받아 검증을 수행하는 API 추가

- src/main/java/kr/co/yourplanet/ypbackend/config/SwaggerConfig.java
> [feat] JwtPrincipal Swagger 문서에 미노출.

- yp-core/src/main/java/kr/co/yourplanet/core/entity/instagram/InstagramMedia.java
- yp-core/src/main/java/kr/co/yourplanet/core/enums/StatusCode.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/controller/InstagramController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/dto/InstagramMediaForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/repository/InstagramMediaRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/service/InstagramService.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/service/impl/InstagramServiceImpl.java
> [feat] instagramMedia 조회 API 개발

- yp-core/src/main/java/kr/co/yourplanet/core/entity/instagram/InstagramMedia.java
> [fix] @Getter 어노테이션 중복 오류 수정

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/InstagramMediaRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
> [fix] InstagramMediaRepository.java 중복생성 수정

- yp-online/src/main/java/kr/co/yourplanet/online/foundation/filter/JwtAuthenticationFilter.java
- yp-online/src/main/java/kr/co/yourplanet/online/jwt/JwtTokenProvider.java
> [feat] JWT 인증토큰 Bearer prefix 추가

- yp-core/src/main/java/kr/co/yourplanet/core/entity/member/Member.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/JoinForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
> [fix] instagramUsername 필드명 수정

- yp-online/src/main/java/kr/co/yourplanet/online/business/user/repository/MemberRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
> [feat] 작가 회원가입시 인스타그램 계정 기가입 여부 확인

- yp-batch/src/main/resources/application.yaml
> [feat] 배치 서비스 포트 변경

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/PriceServiceImpl.java
> [fix] 가격 임시저장 없이 최종저장시 발생하는 오류 수정

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/controller/StudioController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/dao/StudioBasicDao.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/dto/StudioBasicSearch.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/dto/StudioRegisterForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryCustom.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryImpl.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/ProfileService.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
> [feat] Studio 기본 검색 구현

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryCustom.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryImpl.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
> [feat] 예산 최소금액, 최대금액을 통한 검색 추가

- yp-batch/src/main/java/kr/co/yourplanet/batch/InstagramApiManager.java
- yp-batch/src/main/java/kr/co/yourplanet/batch/config/WebClientConfig.java
- yp-batch/src/main/java/kr/co/yourplanet/batch/dto/response/InstagramMediaApiForm.java
- yp-batch/src/main/java/kr/co/yourplanet/batch/job/InstagramBatchWriter.java
> [Batch] 인스타그램 미디어 조회 API paging 처리

- yp-online/src/main/java/kr/co/yourplanet/online/business/instagram/repository/InstagramMediaRepository.java
> [fix] 인스타그램 조회 API 수정. permalink의 키 값 완전 일치해야 조회됨

- yp-core/src/main/java/kr/co/yourplanet/core/enums/StatusCode.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/task/service/TaskService.java
- yp-online/src/main/java/kr/co/yourplanet/online/config/WebSecurityConfig.java
- yp-online/src/main/java/kr/co/yourplanet/online/foundation/filter/JwtAuthenticationFilter.java
- yp-online/src/main/java/kr/co/yourplanet/online/jwt/JwtTokenProvider.java
> [feat] JWT 인증 관련 예외처리 추가

- yp-online/build.gradle
- yp-online/src/main/resources/logback-spring.xml
> [feat] 로그 파일 저장을 위한 logback 설정

- Dockerfile
> [feat] Dockerfile 정의

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/dto/StudioRegisterForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
- yp-online/src/main/java/kr/co/yourplanet/online/common/util/FileManageUtil.java
- yp-online/src/main/resources/application.yaml
> [feat] Studio 프로필 이미지 validation 추가

- yp-core/src/main/java/kr/co/yourplanet/core/entity/member/RefreshToken.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/RefreshAccessTokenForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/repository/RefreshTokenRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
- yp-online/src/main/java/kr/co/yourplanet/online/config/JwtConfig.java
- yp-online/src/main/java/kr/co/yourplanet/online/foundation/filter/JwtAuthenticationFilter.java
- yp-online/src/main/java/kr/co/yourplanet/online/jwt/JwtTokenProvider.java
- yp-online/src/main/java/kr/co/yourplanet/online/properties/JwtProperties.java
- yp-online/src/main/resources/application.yaml
> refresh 토큰 구현

- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/Project.java
- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectHistory.java
- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectHistoryKey.java
- yp-core/src/main/java/kr/co/yourplanet/core/util/LocalDateListConverter.java
- yp-core/src/main/java/kr/co/yourplanet/core/util/StringListConverter.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/request/ProjectNegotiateForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/request/ProjectRequestForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ProjectHistories.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/repository/ProjectRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectService.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/repository/MemberRepository.java
> [feat] 프로젝트 관련 API 1차 커밋 (의뢰, 협상, 거절, 승인)

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
> [fix] keywordType null 처리 추가

- yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/RefreshTokenForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/RefreshTokenResult.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
> [fix] refresh 토큰 갱신 관련 개선

- yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
> [fix] refresh token cookie에 저장

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/controller/StudioController.java
> [refactor] studio API 네이밍 통일 (/studio)

- yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
- yp-online/src/main/java/kr/co/yourplanet/online/foundation/filter/JwtAuthenticationFilter.java
> [fix] 토큰 관련 오류 401 HttpStatus 수정

- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/Project.java
- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectHistory.java
- yp-core/src/main/java/kr/co/yourplanet/core/enums/MemberType.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/request/ProjectNegotiateForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/request/ProjectRequestForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ProjectHistories.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectService.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/dto/JoinForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/service/MemberService.java
> [refactor] 작가 변수명 변경 (author -> creator)

- yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/AuthController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/user/controller/MemberController.java
- yp-online/src/main/java/kr/co/yourplanet/online/config/WebSecurityConfig.java
> [feat] 인증이 불필요한 전용 API 컨트롤러 생성 (로그인, 회원가입 등)

- yp-online/src/main/java/kr/co/yourplanet/online/foundation/filter/JwtAuthenticationFilter.java
- yp-online/src/main/java/kr/co/yourplanet/online/jwt/JwtTokenProvider.java
> [feat] JWT 토큰 예외처리 추가

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/dao/StudioBasicDao.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/repository/StudioRepositoryImpl.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
> [feat] 작가검색 Response 필드 변경 categoryName -> categoryCode

- Dockerfile
- yp-online/src/main/java/kr/co/yourplanet/online/YpBackendApplication.java
> [feat] Timezone 설정

- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/controller/StudioController.java
> [fix] 프로필 사진 미첨부시 오류 해결

- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectReferenceFile.java
- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/ProjectReferenceFileKey.java
- yp-core/src/main/java/kr/co/yourplanet/core/enums/FileType.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/repository/ProjectReferenceFileRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectService.java
- yp-online/src/main/java/kr/co/yourplanet/online/common/util/FileManageUtil.java
- yp-online/src/main/java/kr/co/yourplanet/online/common/util/FileUploadResult.java
- yp-online/src/main/java/kr/co/yourplanet/online/properties/FileProperties.java
- yp-online/src/main/resources/application-dev.yaml
- yp-online/src/main/resources/application-local.yaml
> [feat] 프로젝트 참고자료 업르도 추가

- yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ProjectBasicInfo.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/repository/ProjectHistoryRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/repository/ProjectRepository.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectService.java
> [feat] 사용자기준 전체 프로젝트 조회 추가

- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/Project.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectService.java
> [feat] 프로젝트 일자 관련(의뢰,수락,거절 등) 필드 추가

- yp-core/src/main/java/kr/co/yourplanet/core/entity/project/Project.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/file/FileController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/request/ProjectRequestForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ProjectDetailInfo.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ProjectHistoryForm.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/dto/response/ReferenceFileInfo.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/project/service/ProjectService.java
> [feat] 프로젝트 상세 조회 추가

- .github/workflows/dnrule.yml
- KST 기준 매일 자정 issue와 pr의 d-n 라벨이 자동 갱신되는 워크플로우를 생성했습니다.
아래 액션을 사용하여 구현했습니다.
https://github.com/marketplace/actions/update-d-n-labels
> [YP-626] env: 매일 자정 dn 라벨 자동 갱신 워크플로우 생성

- yp-online/src/main/java/kr/co/yourplanet/online/business/project/controller/ProjectController.java
Jira: YP-640
-  API URL 네이밍 통일
- 작가의 스튜디오 정보를 조회해오는 `GET /creator` API 참고하여 프로젝트 조회 API 네이밍 수정
- AS-IS : `/project/mine`
- TO-BE : `/project`
- 
-
> [YP-640] refactor : Project 리스트 조회 API URL 수정

- .github/workflows/ci.yml
- .gitignore
- yp-batch/src/main/java/kr/co/yourplanet/batch/YpBatchApplication.java
- yp-batch/src/main/resources/application-dev.yaml
- yp-batch/src/main/resources/application-local.yaml
- yp-batch/src/main/resources/application.yaml
- 개발 환경 구축
- 코드가 통합되기 위해서 로컬 환경에서 따로 검증해야하는 과정이 있었습니다.
- github action을 활용한 CI workflow를 작성하여 build 성공 검증을 하는 CI를 자동화했습니다.
- 의존성 취약점을 체크해주는 dependabot을 적용하여 `main` 브랜치에서 트리거 되는 경우 alert를 생성하도록 설정하였습니다.
해당 기능은 아직 검증 되지 않아 `main`에 push 후 추가 PR이 필요할 수 있습니다.
- dependabot alert는 기본 브런치의 의존성 데이터에만 적용되므로 main에 push할 때도 workflow가 trigger되도록 작성했습니다.
- 추가를 원하시는 기능이 있다면 코멘트로 남겨주세요!
- Gradle을 사용하여 Java 빌드 및 테스트
https://docs.github.com/ko/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-gradle
- setup gradle action
https://github.com/gradle/actions
- dependabot 빠른 시작 가이드
https://docs.github.com/ko/code-security/getting-started/dependabot-quickstart-guide#prerequisites
> [YP-623] env: CI 워크플로우 작성

- yp-core/src/main/java/kr/co/yourplanet/core/enums/FileType.java
- yp-online/src/main/java/kr/co/yourplanet/online/business/studio/service/impl/ProfileServiceImpl.java
- yp-online/src/main/java/kr/co/yourplanet/online/common/util/FileManageUtil.java
Jira: YP-591
- Project - 참고자료에 대한 파일 확장자 제한
- `FileManageUtil.validateFile()` : 파일에 대한 유효성 체크 메소드 공통화 진행하였습니다.
```java
validateFile() {
//...파일 유효성 체크 공통로직
if null ...
// FileType별로 추가적인 유효성 체크 수행
switch (FileType) {
case : 프로필이미지
case : 프로젝트_첨부파일
...
}
```
- 
-
> [YP-591] refactor : 파일 유효성 검사 공통화

- .github/workflows/_notify.yml
- .github/workflows/ci.yml
- .github/workflows/cicd-dev.yml
- Dockerfile
- dev, main 브런치 merge 시 배포 자동화와 배포 성공 시 디스코드 알림을 위한 워크플로우를 작성했습니다.
- 이전에 ci 워크플로우에 추가했던 dependa bot에서 실행되는 액션들이 에러가 발생해서 우선은 job을 임시 삭제해두었습니다.
- 알림 메시지에 추가로 포함되면 좋을 내용이 있다면 제안 부탁드립니다.
> [YP-755] env: cicd, discord 알림 workflow 구현

- .github/workflows/_notify.yml
- .github/workflows/cicd-dev.yml
- 커밋 메시지에 이스케이프 문자 추가로 JSON 형식 오류가 발생했습니다.
- jq 명령어로 JSON을 변환하여 안전하게 보내도록 수정했습니다.
> [YP-755] notify workflow JSON message format 오류 해결
